/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_img_jk_beethelion_MatchingLib */

#ifndef _Included_com_img_jk_beethelion_MatchingLib
#define _Included_com_img_jk_beethelion_MatchingLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_img_jk_beethelion_MatchingLib
 * Method:    jkMatching
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_img_jk_beethelion_MatchingLib_jkMatching
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
